server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: tung
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql


